# Standalone deployment of this web service
version: "3.8"

# Establish communication between services
networks:
  app-tier:
    driver: bridge

services:
  # MongoDB database service
  mongodb:
    image: bitnami/mongodb:${MONGODB_VERSION}
    environment:
      - MONGODB_ENABLE_JOURNAL=false
      - MONGODB_PORT_NUMBER=${MONGODB_PORT:-27017}
      - MONGODB_DATABASE
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
    networks:
      - app-tier
    volumes:
      - type: bind
        source: ./data-persistence
        target: /bitnami/mongodb

  # Service for this project
  api:
    image: registry.gitlab.com/france-atelier/templates/template-backend-fastify:${APP_VERSION}
    environment:
      # Port the server must listen to
      - PORT=${APP_PORT}
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Database credentials
      - MONGODB_HOST=mongodb:${MONGODB_PORT:-27017}
      - MONGODB_DATABASE
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_SECURE=off # always off in Docker
      # Other environment variables
    networks:
      - app-tier
    ports:
      - ${APP_PORT}:${APP_PORT}
