name: pdf-service
on:
# The workflow build will only run when a push event occurs on the branches bellow 
# and at least one path will be affected.
  push:
    branches:
    - main
    paths:
    - src/*
    - src/**/*
    - src/**/**/*
    - src/**/**/**/*
    - src/**/**/**/**/*
    - package*.json
    - .github/**/*
jobs:
  docker_build:
    runs-on: ubuntu-latest
    env:
     DOCKER_IMAGE_NAME: ghcr.io/keybas-engineering/pdf-service/pdf-service
     NPM_AUTH_TOKEN: ${{ secrets.NPM_READ_PACKAGE_REGISTRY }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Post Build
        run: |
         echo "@keybas-engineering:registry=https://npm.pkg.github.com" > .npmrc
         echo //npm.pkg.github.com/:_authToken=\"${{env.NPM_AUTH_TOKEN}}\" >> .npmrc
      - name: Get Version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}             
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=${{env.DOCKER_IMAGE_NAME}}:latest
          cache-to: type=inline
          tags: ${{env.DOCKER_IMAGE_NAME}}:${{env.VERSION}},${{env.DOCKER_IMAGE_NAME}}:latest